global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using SuperDuperMart.Api.Authorization;
global using SuperDuperMart.Api.Exceptions.Handlers;
global using SuperDuperMart.Api.Extensions;
global using SuperDuperMart.Core.Entities;
global using SuperDuperMart.Core.Interfaces;
global using SuperDuperMart.Core.Models;
global using SuperDuperMart.Persistence;
