global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using SuperDuperMart.Api.Authorization;
global using SuperDuperMart.Api.ExceptionHandlers;
global using SuperDuperMart.Core.Entities;
global using SuperDuperMart.Core.Interfaces;
global using SuperDuperMart.Shared.Models.Products;
global using SuperDuperMart.Shared.Models.Users;
global using AutoMapper;