name: Publish Api ⚙️

on:
  push:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: "superdupermart-api"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install dependencies
      run: dotnet restore ./src/SuperDuperMart.Api/SuperDuperMart.Api.csproj
      
    - name: Build
      run: dotnet build ./src/SuperDuperMart.Api/SuperDuperMart.Api.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./src/SuperDuperMart.Api/SuperDuperMart.Api.csproj --configuration Release --output ./publish

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_API_PUBLISH_PROFILE }}
        package: ./publish
